name: build check

on:
  workflow_dispatch:
  push:
   branches:
        - master
        - develop
  pull_request:
    types: [opened, reopened, synchronize]

env:
  NODE_VERSION: "14.15.3"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      # https://github.com/actions/cache/blob/main/examples.md#node---yarn-2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn

      - name: lint
        run: yarn lint

      - name: build
        if: always()
        run: yarn build

      - name: storybook
        if: always()
        run: yarn nuxt storybook build

      - name: Upload test artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-artifacts
          path: storybook-static
          retention-days: 3
